"""Initial migration - OneRoster entities

Revision ID: e47c6d512932
Revises: 
Create Date: 2025-05-25 14:48:15.997102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47c6d512932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_sessions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('schoolYear', sa.String(length=10), nullable=False),
    sa.Column('sourcedId', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dateLastModified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('FirstSeenDateTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('LastSeenDateTime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sourcedId')
    )
    op.create_index(op.f('ix_academic_sessions_sourcedId'), 'academic_sessions', ['sourcedId'], unique=False)
    op.create_table('orgs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('sourcedId', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dateLastModified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('FirstSeenDateTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('LastSeenDateTime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sourcedId')
    )
    op.create_index(op.f('ix_orgs_sourcedId'), 'orgs', ['sourcedId'], unique=False)
    op.create_table('users',
    sa.Column('enabledUser', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('givenName', sa.String(length=255), nullable=False),
    sa.Column('familyName', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sms', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('sourcedId', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dateLastModified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('FirstSeenDateTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('LastSeenDateTime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sourcedId')
    )
    op.create_index(op.f('ix_users_sourcedId'), 'users', ['sourcedId'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_sourcedId'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orgs_sourcedId'), table_name='orgs')
    op.drop_table('orgs')
    op.drop_index(op.f('ix_academic_sessions_sourcedId'), table_name='academic_sessions')
    op.drop_table('academic_sessions')
    # ### end Alembic commands ###
